BOT_VERSION = 1
VERSION_KEY = "version"

IGNORED_ITEMS = {
    "Nothing",
    "Recovery Heart",
    "Piece of Heart",
    "Heart Container",
    "Small Magic Jar",
    "Large Magic Jar",
    "Deku Stick",
    "Fairy",
    "10 Arrows",
    "30 Arrows",
    "1 Bombchu",
    "5 Bombchu",
    "10 Bombchu",
    "5 Bombs",
    "10 Bombs",
    "10 Deku Nuts",
    "Green Rupee",
    "Blue Rupee",
    "Red Rupee",
    "Purple Rupee",
    "Silver Rupee",
    "Gold Rupee",
    "Green Potion",
    "Ocean Skulltula Token",
    "Swamp Skulltula Token",
    "Owl Statue (Clock Town)",
    "Owl Statue (Milk Road)",
    "Owl Statue (Southern Swamp)",
    "Owl Statue (Woodfall)",
    "Owl Statue (Mountain Village)",
    "Owl Statue (Snowhead)",
    "Owl Statue (Great Bay)",
    "Owl Statue (Zora Cape)",
    "Owl Statue (Ikana Canyon)",
    "Owl Statue (Stone Tower)",
}

STANDARD_ITEM_ALIASES = {
    "bow": "heros bow",
    "cow mask": "romanis mask",
    "magic": "magic upgrade",
    "magic power": "magic upgrade",
    "scale": "progressive scale",
    "sniffa": "mask of scents",
    "strength": "progressive strength",
    "sword": "progressive sword",
    "wallet": "progressive wallet",
}

STANDARD_LOCATION_ALIASES = {
    "gbt": "temple great bay",
    "great bay temple": "temple great bay",
    "istt": "temple stone tower inverted",
    "inverted stone tower temple": "temple stone tower inverted",
    "osh": "spider house ocean",
    "ocean spider house": "spider house ocean",
    "pf": "pirate fortress",
    "pirates fortress": "pirate fortress",
    "sht": "temple snowhead",
    "snowhead temple": "temple snowhead",
    "ssh": "spider house swamp",
    "swamp spider house": "spider house swamp",
    "stt": "temple stone tower",
    "stone tower temple": "temple stone tower",
    "wft": "temple woodfall",
    "woodfall temple": "temple woodfall",
}