BOT_VERSION = 1
VERSION_KEY = "version"

IGNORED_ITEMS = {
    "Nothing",
    "Recovery Heart",
    "Piece of Heart",
    "Heart Container",
    "Small Magic Jar",
    "Large Magic Jar",
    "Deku Stick",
    "Fairy",
    "10 Arrows",
    "30 Arrows",
    "1 Bombchu",
    "5 Bombchu",
    "10 Bombchu",
    "5 Bombs",
    "10 Bombs",
    "10 Deku Nuts",
    "Green Rupee",
    "Blue Rupee",
    "Red Rupee",
    "Purple Rupee",
    "Silver Rupee",
    "Gold Rupee",
    "Green Potion",
    "Ocean Skulltula Token",
    "Swamp Skulltula Token",
}

LOCATION_NAME_REFORMATS = {
    "MM_SPIDER_HOUSE_SWAMP": "Swamp Spider House",
    "MM_SPIDER_HOUSE_OCEAN": "Ocean Spider House",
    "MM_TEMPLE_WOODFALL": "Woodfall Temple",
    "MM_BOSS_TEMPLE_WOODFALL": "Woodfall Temple Boss",
    "MM_TEMPLE_SNOWHEAD": "Snowhead Temple",
    "MM_BOSS_TEMPLE_SNOWHEAD": "Snowhead Temple Boss",
    "MM_TEMPLE_GREAT_BAY": "Great Bay Temple",
    "MM_BOSS_TEMPLE_GREAT_BAY": "Great Bay Temple Boss",
    "MM_TEMPLE_STONE_TOWER": "Stone Tower Temple",
    "MM_TEMPLE_STONE_TOWER_INVERTED": "Inverted Stone Tower Temple",
    "MM_BOSS_TEMPLE_STONE_TOWER": "Stone Tower Temple Boss",
}

STANDARD_ITEM_ALIASES = {
    "bow": "heros bow",
    "bremen": "bremen mask",
    "couples": "couples mask",
    "cow mask": "romanis mask",
    "don gero": "don geros mask",
    "frog": "don geros mask",
    "frog mask": "don geros mask",
    "fd": "fierce deitys mask",
    "fierce deity": "fierce deitys mask",
    "gorman mask": "circus leaders mask",
    "gibdo": "gibdo mask",
    "kamaro": "kamaros mask",
    "kamaros": "kamaros mask",
    "keaton": "keaton mask",
    "keg": "powder keg",
    "kegw": "powder keg",
    "pig mask": "mask of scents",
    "sniffa": "mask of scents",
    "deku": "deku mask",
    "goron": "goron mask",
    "zora": "zora mask",
    "sonata": "sonata of awakening",
    "lullaby": "goron lullaby",
    "nwbn": "new wave bossa nova",
    "new wave": "new wave bossa nova",
    "elegy": "elegy of emptiness",
    "magic": "magic upgrade",
    "magic power": "magic upgrade",
    "scale": "progressive scale",
    "strength": "progressive strength",
    "sword": "progressive sword",
    "wallet": "progressive wallet",
}

STANDARD_CHECK_ALIASES = {
    "soundcheck": "milk bar troupe leader mask",
    "sound check": "milk bar troupe leader mask",
    "anju and kafei": "stock pot inn couples mask",
    "gossips": "termina field gossip stones hp",
    "gorman race": "gorman track garo mask",
    "grog": "cucco shack bunny mask",
    "lemons": "cucco shack bunny mask",
    "aliens": "romani ranch aliens",
    "cremia": "romani ranch cremia escort",
    "boat archery": "tourist information boat archery",
    "butler": "deku shrine mask of scents",
    "hungry goron": "mountain village don gero mask",
    "hugo": "mountain village don gero mask",
    "smithy 1": "blacksmith razor blade",
    "smithy 2": "blacksmith gilded sword",
    "darmani": "goron graveyard mask",
    "goron race": "goron race reward",
    "mikau": "great bay coast zora mask",
    "seahorses": "pinnacle rock hp",
    "beavers": "waterfall rapids beaver race 1",
    "fisherman": "great bay coast fisherman hp",
    "dampe": "beneath the graveyard dampe chest",
    "pamela": "music box house gibdo mask",
    "pamela's father": "music box house gibdo mask",
    "poe hut": "ghost hut hp",
}

STANDARD_LOCATION_ALIASES = {
    "gbt": "great bay temple",
    "istt": "inverted stone tower temple",
    "osh": "ocean spider house",
    "pf": "pirate fortress",
    "pirates fortress": "pirate fortress",
    "sht": "snowhead temple",
    "ssh": "swamp spider house",
    "stt": "stone tower temple",
    "wft": "woodfall temple",
}
